// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeitpDYCD6fIDAQfQOIOS8SZF1vivrfU',
    appId: '1:488723151812:web:38cead618b67f484664291',
    messagingSenderId: '488723151812',
    projectId: 'donation-fbf6a',
    authDomain: 'donation-fbf6a.firebaseapp.com',
    storageBucket: 'donation-fbf6a.firebasestorage.app',
    measurementId: 'G-264W2EF1PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNy8hr-X6nEzOXdZQkrWid0ydeGKUBCk',
    appId: '1:488723151812:android:a24c6b3e0a049f60664291',
    messagingSenderId: '488723151812',
    projectId: 'donation-fbf6a',
    storageBucket: 'donation-fbf6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuKCe-NdocnaVHBxbpmyW98PgjM6ayZWU',
    appId: '1:488723151812:ios:b35f34f91cfc63b1664291',
    messagingSenderId: '488723151812',
    projectId: 'donation-fbf6a',
    storageBucket: 'donation-fbf6a.firebasestorage.app',
    iosBundleId: 'com.example.donationCodenest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuKCe-NdocnaVHBxbpmyW98PgjM6ayZWU',
    appId: '1:488723151812:ios:b35f34f91cfc63b1664291',
    messagingSenderId: '488723151812',
    projectId: 'donation-fbf6a',
    storageBucket: 'donation-fbf6a.firebasestorage.app',
    iosBundleId: 'com.example.donationCodenest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMeitpDYCD6fIDAQfQOIOS8SZF1vivrfU',
    appId: '1:488723151812:web:07557e20896cbc44664291',
    messagingSenderId: '488723151812',
    projectId: 'donation-fbf6a',
    authDomain: 'donation-fbf6a.firebaseapp.com',
    storageBucket: 'donation-fbf6a.firebasestorage.app',
    measurementId: 'G-P46848J434',
  );
}
